title: My Awesome Blog
author: your name
email: your e-mail
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: your username
twitter_username: your username
instagram_username: your username
linkedin_username: your username

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami-bilingual
exclude:
  - Gemfile
  - Gemfile.lock